### ISSUE TITLE
Please add docs, literally any docs

### ISSUE THREAD

**Issue by red8888** [SonarSource/sonar-iac#355]
Is this the exe used to scan terraform configs with sonarcloud? I keep seeing announcements this is available now and I can scan terraform with sonar cloud, but no actual documentation.

Anything thats just a simple setup doc would be nice. An example command for how to scan a terraform directory or directory hierarchy, etc.

Really want to use this, I pay for sonarcloud and want to add terraform scanning to all the other stuff I currently scan. It's weird this was released with zero documentation- maybe I'm dumb and just can't find it.

**Comment by Lerentis** [comment]
Hi @red8888 ,

you can use the sonar-scanner-cli to scan terraform/cloudformation code and if you are on sonarcloud terraform is also available with autoscan. you can find more information in the general docs:

* https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
* https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-cli/
* https://docs.sonarcloud.io/advanced-setup/automatic-analysis/

i am currently really just running the sonar-scanner-cli like this: 

```bash
sonar-scanner \
  -Dsonar.projectKey=$SONAR_PROJECT\
  -Dsonar.sources=. \
  -Dsonar.host.url=$SONAR_URL \
  -Dsonar.login=$SONAR_TOKEN
```

hope that helps you get started :)
